# Generated by Django 5.1.2 on 2026-05-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_notes'),
    ]

    operations = [
        migrations.RunSQL(
            # primero se elimina el indice que SQLite tiene sobre goal_id
            # sin este paso SQLite no permite hacer DROP COLUMN
            sql="DROP INDEX IF EXISTS appointments_appointment_goal_id_c0aa9fa0;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            # el campo era ForeignKey asi que la columna real en la DB es goal_id
            sql="ALTER TABLE appointments_appointment DROP COLUMN goal_id;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='goal',
        ),
    ]
